services:
  - type: web
    name: slice-and-fire-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@sliceandfire.com
      - key: ADMIN_ALERT_EMAIL
        value: admin@sliceandfire.com
