import { useState } from 'react'
import './App.css'

type Pizza = { id: number; name: string; description: string; price: number; color: string; rating: string }
const pizzas: Pizza[] = [
  { id: 1, name: 'Margherita DOC', description: 'San Marzano tomatoes, buffalo mozzarella, basil.', price: 14.5, color: '#a5261e', rating: '4.9 (98)' },
  { id: 2, name: 'Diavola Fire', description: 'Spicy soppressata, charred peppers, smoked red chili.', price: 16, color: '#a63b1d', rating: '4.8 (120)' },
  { id: 3, name: 'White Truffle', description: 'Truffle cream, mozzarella, wild mushrooms, thyme.', price: 18.5, color: '#473b22', rating: '4.9 (76)' },
  { id: 4, name: 'Pistachio Pesto', description: 'Pistachio pesto, fior di latte, crushed pistachios.', price: 17, color: '#795158', rating: '4.7 (54)' },
  { id: 5, name: 'Quattro Formaggi', description: 'Mozzarella, gorgonzola, parmesan, provolone.', price: 17.5, color: '#ab762b', rating: '4.8 (86)' },
  { id: 6, name: 'Prosciutto e Rucola', description: 'Tomatoes, prosciutto, arugula, parmesan.', price: 18, color: '#932d25', rating: '4.8 (89)' },
]
type Page = 'home' | 'menu' | 'customize' | 'cart'

export default function App() {
  const [page, setPage] = useState<Page>('home')
  const [cart, setCart] = useState<Record<number, number>>({ 2: 1 })
  const [selected, setSelected] = useState(pizzas[1])
  const add = (pizza: Pizza) => setCart((value) => ({ ...value, [pizza.id]: (value[pizza.id] ?? 0) + 1 }))
  const select = (pizza: Pizza) => { setSelected(pizza); setPage('customize'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const count = Object.values(cart).reduce((a, b) => a + b, 0)
  return <main className="app-shell"><p className="page-label">{page === 'customize' ? 'Customize Pie' : page[0].toUpperCase() + page.slice(1)}</p><section className="site-frame">
    <Header page={page} setPage={setPage} count={count} />
    {page === 'home' && <Home setPage={setPage} add={add} />}
    {page === 'menu' && <Menu add={add} select={select} />}
    {page === 'customize' && <Customize pizza={selected} add={add} setPage={setPage} />}
    {page === 'cart' && <Cart cart={cart} setCart={setCart} setPage={setPage} />}
    {page === 'home' && <Footer setPage={setPage} />}
  </section></main>
}

function Header({ page, setPage, count }: { page: Page; setPage: (p: Page) => void; count: number }) { return <header className="header"><button className="brand" onClick={() => setPage('home')}><i /><span><b>Slice &amp; Fire</b><small>Wood-Fired Artisan</small></span></button><nav>{(['home', 'menu'] as Page[]).map((item) => <button className={page === item ? 'active' : ''} onClick={() => setPage(item)} key={item}>{item[0].toUpperCase() + item.slice(1)}</button>)}<button>Locations</button><button>About</button><button>Careers</button></nav><div className="header-actions"><button className="sign-in">Sign In</button><button className="cart-pill" onClick={() => setPage('cart')}>Cart ({count})</button></div></header> }
function Home({ setPage, add }: { setPage: (p: Page) => void; add: (p: Pizza) => void }) { return <><section className="hero"><div><span className="eyebrow">TODAY’S SPECIAL</span><h1>Charred Perfection,<br />Baked to Order.</h1><p>Get 20% off our signature Diavola with a drizzle of hot honey. Hand-stretched dough, fired at 900°F, delivered to your door.</p><p className="actions"><button className="primary" onClick={() => setPage('menu')}>Order Now</button><button className="outline" onClick={() => setPage('menu')}>View Menu</button></p></div><div className="hero-art">Wood-Fired Diavola</div></section><section className="favorites"><div className="chips"><button className="chosen">♨ Wood-Fired</button><button>White Pies</button><button>Spicy</button><button>Vegan</button><button>Sides</button></div><div className="section-title"><h2>Artisan Favorites</h2><button onClick={() => setPage('menu')}>See All →</button></div><div className="grid home-grid">{pizzas.slice(0, 4).map((pizza) => <Card pizza={pizza} add={add} key={pizza.id} />)}</div></section></> }
function Menu({ add, select }: { add: (p: Pizza) => void; select: (p: Pizza) => void }) { return <section className="page menu"><h1>Artisan Pizza Menu</h1><p>Hand-stretched dough, wood-fired to perfection.</p><div className="tabs"><button className="active">Pizzas</button><button>Appetizers</button><button>Salads</button><button>Drinks &amp; Desserts</button></div><div className="grid menu-grid">{pizzas.map((pizza) => <Card compact pizza={pizza} add={add} select={select} key={pizza.id} />)}</div></section> }
function Card({ pizza, add, select, compact }: { pizza: Pizza; add: (p: Pizza) => void; select?: (p: Pizza) => void; compact?: boolean }) { return <article className={`card ${compact ? 'compact' : ''}`}><button className="pizza-art" aria-label={`Customize ${pizza.name}`} style={{ background: pizza.color }} onClick={() => select?.(pizza)} /><div className="card-copy"><div><h3>{pizza.name}</h3><p>{pizza.description}</p><small>★ {pizza.rating}</small><strong>${pizza.price.toFixed(2)}</strong></div><button className="add" onClick={() => add(pizza)}>+ Add</button></div></article> }
function Customize({ pizza, add, setPage }: { pizza: Pizza; add: (p: Pizza) => void; setPage: (p: Page) => void }) { const [size, setSize] = useState('Artisan 12”'); const [crust, setCrust] = useState('Traditional Wood-Fired Neapolitan'); return <section className="page customize"><p className="crumb">Menu / <b>{pizza.name}</b></p><div className="customize-layout"><div className="large-art" style={{ background: pizza.color }}><span>♨ WOOD-FIRED</span></div><div className="customize-copy"><h1>{pizza.name}</h1><p>{pizza.description} A savory Neapolitan tradition, baked at high heat with a crisp, charred crust.</p><Choices label="Choose Size" values={['Personal 10”', 'Artisan 12”', 'Family 14”']} current={size} choose={setSize} /><Choices label="Crust Selection" values={['Traditional Wood-Fired Neapolitan', 'Thick Sicilian Pan']} current={crust} choose={setCrust} /><Choices label="Add Extra Toppings" values={['Extra Mozz +$2.00', 'Hot Honey +$1.50', 'Basil +$0.50']} current="" choose={() => {}} /><div className="price-row"><div><small>Total Price</small><b>${pizza.price.toFixed(2)}</b></div><button className="primary" onClick={() => { add(pizza); setPage('cart') }}>Add to Order</button></div></div></div></section> }
function Choices({ label, values, current, choose }: { label: string; values: string[]; current: string; choose: (x: string) => void }) { return <div className="choice"><b>{label}</b><div>{values.map((value) => <button className={current === value ? 'picked' : ''} onClick={() => choose(value)} key={value}>{value}</button>)}</div></div> }
function Cart({ cart, setCart }: { cart: Record<number, number>; setCart: (x: Record<number, number>) => void; setPage: (p: Page) => void }) { const items = pizzas.filter((p) => cart[p.id]); const subtotal = items.reduce((sum, p) => sum + p.price * cart[p.id], 0); const delivery = items.length ? 3.5 : 0; const tax = subtotal * .08; const change = (id: number, amount: number) => { const next = Math.max(0, (cart[id] ?? 0) + amount); if (!next) { const { [id]: gone, ...rest } = cart; setCart(rest) } else setCart({ ...cart, [id]: next }) }; return <section className="page cart"><h1>My Cart</h1><div className="cart-layout"><div className="cart-items">{items.length ? items.map((pizza) => <article className="cart-item" key={pizza.id}><span style={{ background: pizza.color }} /><div><h3>{pizza.name} <small>(12”)</small></h3><p>{pizza.description}</p><strong>${(pizza.price * cart[pizza.id]).toFixed(2)}</strong></div><div className="quantity"><button onClick={() => change(pizza.id, -1)}>−</button><b>{cart[pizza.id]}</b><button onClick={() => change(pizza.id, 1)}>+</button></div></article>) : <p className="empty">Your cart is ready for something delicious.</p>}<input placeholder="Enter coupon or promo code" /></div><aside><h3>Order Total</h3><p><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></p><p><span>Delivery Fee</span><span>${delivery.toFixed(2)}</span></p><p><span>Tax (8%)</span><span>${tax.toFixed(2)}</span></p><hr /><p className="total"><b>Final Total</b><b>${(subtotal + delivery + tax).toFixed(2)}</b></p><button className="primary" disabled={!items.length}>Proceed to Checkout</button></aside></div></section> }
function Footer({ setPage }: { setPage: (p: Page) => void }) { return <footer><div><h3>Slice &amp; Fire</h3><p>Wood-fired artisan pizza,<br />crafted across town.</p></div><div><b>Explore</b><button onClick={() => setPage('menu')}>Menu</button><button>Locations</button><button>Gift Cards</button><button>Careers</button></div><div><b>Support</b><button>Contact Us</button><button>FAQs</button><button>Track Order</button></div><div><b>Contact</b><p>Trattoria 2nd Ave, NY<br />(212) 555-0194<br />hello@sliceandfire.com</p></div><small>© 2026 Slice &amp; Fire. All rights reserved.</small></footer> }
